Mayhem
mayhemheroes/mle pull request #1
Opened 2022-05-17 03:47 UTC by capuanob

This includes my contributions for harnessing MLE with Mayhem. Please let me know if anything needs to be adjusted!

2022-06-08 22:51 UTC, xansec requested changes
Please do not modify source unless necessary (i.e. build is broken). I don't think upstream will accept your changes as is. I would create maybe a new module or `fuzz` folder, and create a fuzz target in there rather than modifying existing source.

2022-06-08 22:51 UTC, xansec commented on Makefile
> -mle_cflags:=-std=c99 -Wall -Wextra -pedantic -Wno-pointer-arith -Wno-unused-result -Wno-unused-parameter -g -O0 -D_GNU_SOURCE -I. $(CFLAGS)
You should be able to pass `-fsanitize=fuzzer` in the `CFLAGS` environment variable without modifying the Makefile.

2022-06-09 00:12 UTC, capuanob commented
Did a total rework on fuzzing harness to be 1) More accurate to how MLE would truly be used and 2) Prevent making source code changes

2022-06-09 03:36 UTC, xansec commented
Great improvement!

2022-06-09 03:36 UTC, merged